source 'https://rubygems.org'

gem 'fastlane'
gem 'fiddle'
gem 'abbrev'
gem 'ostruct'

plugins_path = File.join(File.dirname(__FILE), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)