name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - development

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Accept Android SDK Licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Install Flutter dependencies
        run: |
          flutter pub get
          if [ $? -ne 0 ]; then
            echo "Dependency resolution failed. Checking outdated packages..."
            flutter pub outdated
            exit 1
          fi
        working-directory: .

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
          working-directory: android

      - name: Add Linux platform and install Ruby dependencies
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install --jobs 4
        working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android